# Generated by Django 3.0 on 2020-06-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('content_1', models.CharField(max_length=20)),
                ('content_2', models.CharField(blank=True, max_length=20)),
                ('content_3', models.CharField(blank=True, max_length=20)),
                ('conten_4', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
