# Generated by Django 3.0 on 2020-06-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
